version: "3.1"
services:
  db:
    image: postgres
    container_name: events-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  api:
    container_name: events-api
    restart: always
    build: ./api
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:example@events-db:5432/events
    ports:
      - 5000:5000
    volumes:
      - ./api/:/workspace/api
      - /workspace/api/node_modules
  spa:
    container_name: events-spa
    restart: always
    build: ./spa
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./spa/:/workspace/spa
      - /workspace/spa/node_modules
